// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	UID                  string   `protobuf:"bytes,5,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_c9a04f1999a009fa, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type UsersRequest struct {
	All                  bool     `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_c9a04f1999a009fa, []int{1}
}
func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (dst *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(dst, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *UsersRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Response struct {
	Create               bool     `protobuf:"varint,1,opt,name=create,proto3" json:"create,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_c9a04f1999a009fa, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*UsersRequest)(nil), "go.micro.srv.user.UsersRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_user_c9a04f1999a009fa) }

var fileDescriptor_user_c9a04f1999a009fa = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x1b, 0x93, 0x96, 0x64, 0xea, 0x41, 0x17, 0x3f, 0x42, 0x8a, 0x28, 0x39, 0x09, 0xc2,
	0x2a, 0x15, 0x7c, 0x01, 0x0b, 0xea, 0x45, 0x61, 0xa5, 0x67, 0x59, 0xe3, 0x28, 0x81, 0x24, 0x1b,
	0x77, 0x37, 0xf5, 0x25, 0x7c, 0x05, 0xdf, 0x55, 0x66, 0xd2, 0x9c, 0x34, 0x97, 0xb0, 0xff, 0xf9,
	0xcd, 0xc7, 0x7f, 0x26, 0x70, 0xd8, 0x5a, 0xe3, 0xcd, 0x65, 0xe7, 0xd0, 0xf2, 0x47, 0xb2, 0x16,
	0xfb, 0x1f, 0x46, 0xd6, 0x65, 0x61, 0x8d, 0x74, 0x76, 0x23, 0x09, 0xe4, 0xdf, 0x01, 0x44, 0x6b,
	0x87, 0x56, 0x9c, 0x00, 0xbc, 0x97, 0xd6, 0xf9, 0x97, 0x46, 0xd7, 0x98, 0x06, 0x67, 0xc1, 0x79,
	0xa2, 0x12, 0x8e, 0x3c, 0xea, 0x1a, 0xc5, 0x02, 0x92, 0x4a, 0x0f, 0x74, 0x87, 0x69, 0x4c, 0x01,
	0x86, 0x19, 0xc4, 0xd4, 0x8c, 0x59, 0xd8, 0xb3, 0x41, 0x13, 0x6b, 0xb5, 0x73, 0x5f, 0xc6, 0xbe,
	0xa5, 0x51, 0xcf, 0x06, 0x2d, 0xf6, 0x20, 0x5c, 0x3f, 0xac, 0xd2, 0x29, 0x87, 0xe9, 0x99, 0xdf,
	0xc0, 0x2e, 0xb9, 0x71, 0x0a, 0x3f, 0x3b, 0x74, 0x9e, 0x32, 0x74, 0x55, 0xb1, 0x9d, 0x58, 0xd1,
	0x53, 0x1c, 0xc0, 0xb4, 0x30, 0x5d, 0xe3, 0xd9, 0x44, 0xa8, 0x7a, 0x91, 0x3f, 0x41, 0xac, 0xd0,
	0xb5, 0xa6, 0x71, 0x28, 0x8e, 0x60, 0x56, 0x58, 0xd4, 0x1e, 0xb7, 0x65, 0x5b, 0x25, 0x2e, 0x20,
	0x22, 0x57, 0x5c, 0x38, 0x5f, 0x1e, 0xcb, 0x3f, 0xc7, 0x90, 0x34, 0x5a, 0x71, 0xd2, 0xf2, 0x27,
	0x80, 0x39, 0xc9, 0x67, 0xb4, 0x9b, 0xb2, 0x40, 0xb1, 0x02, 0xb8, 0xe5, 0x36, 0x7c, 0xac, 0xb1,
	0xe2, 0x6c, 0xf1, 0x0f, 0x18, 0x8c, 0xe5, 0x13, 0x71, 0x0f, 0xf1, 0x1d, 0x7a, 0xde, 0x50, 0x9c,
	0x8e, 0xf4, 0x18, 0x76, 0xcf, 0xc6, 0x86, 0xe4, 0x93, 0xab, 0xe0, 0x75, 0xc6, 0x7f, 0xf4, 0xfa,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x6a, 0x16, 0x80, 0xea, 0x01, 0x00, 0x00,
}
