apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: user-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-client
    spec:
      containers:
        - name: user-client
          command: [
		"user-client",
		"--server_address=0.0.0.0:8080",
		"--broker_address=0.0.0.0:10001"
	  ]
          image: turbine-user-client
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: user-port
