apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: login
  name: login
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: login
    spec:
      containers:
      - name: login
        image: sleyva97/login-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
