// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/authentication/authentication.proto

/*
Package authentication is a generated protocol buffer package.

It is generated from these files:
	proto/authentication/authentication.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	RegisterRequest
	RegisterResponse
*/
package authentication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token     string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LoginResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type RegisterRequest struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Password  string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Created   bool   `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	UID       string `protobuf:"bytes,3,opt,name=UID" json:"UID,omitempty"`
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,5,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *RegisterResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *RegisterResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
}

func init() { proto.RegisterFile("proto/authentication/authentication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x4a, 0xf5, 0x30,
	0x10, 0xa5, 0x7f, 0xdf, 0xd7, 0x0e, 0x5e, 0xad, 0x45, 0xa1, 0x54, 0x04, 0xe9, 0x42, 0x74, 0xd3,
	0x0b, 0xfa, 0x04, 0x82, 0x08, 0x82, 0xb8, 0xa8, 0xb8, 0x96, 0xd8, 0x3b, 0x5e, 0x83, 0x9a, 0xd4,
	0x24, 0xd5, 0x95, 0x4b, 0x5f, 0xc1, 0xe7, 0x95, 0xa4, 0x8d, 0x9a, 0x2c, 0xba, 0xcb, 0x99, 0x93,
	0x9c, 0xcc, 0x39, 0x33, 0x70, 0xdc, 0x0b, 0xae, 0xf8, 0x92, 0x0c, 0xea, 0x11, 0x99, 0xa2, 0x1d,
	0x51, 0x94, 0x33, 0x0f, 0x36, 0xe6, 0x4e, 0x7d, 0x01, 0x1b, 0x57, 0x7c, 0x4d, 0x59, 0x8b, 0xaf,
	0x03, 0x4a, 0x55, 0x54, 0x90, 0x0e, 0x12, 0x05, 0x23, 0x2f, 0x58, 0x06, 0x07, 0xc1, 0x51, 0xd6,
	0xfe, 0x60, 0xcd, 0xf5, 0x44, 0xca, 0x77, 0x2e, 0x56, 0x65, 0x38, 0x72, 0x16, 0xd7, 0x1f, 0xb0,
	0x98, 0x74, 0x64, 0xcf, 0x99, 0xc4, 0x62, 0x07, 0x12, 0xc5, 0x9f, 0x90, 0x4d, 0x2a, 0x23, 0x70,
	0xe4, 0x43, 0x4f, 0x7e, 0x1f, 0xe0, 0x81, 0x0a, 0xa9, 0xee, 0x0c, 0x1b, 0x19, 0x36, 0x33, 0x95,
	0x6b, 0x4d, 0xef, 0x41, 0xf6, 0x4c, 0x2c, 0x1b, 0x8f, 0x6f, 0x75, 0x41, 0x93, 0xf5, 0x67, 0x00,
	0x5b, 0x2d, 0xae, 0xa9, 0x54, 0x28, 0xac, 0x15, 0x57, 0x2f, 0x98, 0xd5, 0x0b, 0x5d, 0x3d, 0xa7,
	0xcf, 0x68, 0x26, 0x86, 0xd8, 0x8b, 0xe1, 0x2b, 0x80, 0xfc, 0xb7, 0x8f, 0x29, 0x8a, 0x12, 0xfe,
	0x77, 0x02, 0x89, 0xc2, 0x95, 0xe9, 0x22, 0x6d, 0x2d, 0x9c, 0x8d, 0x23, 0x87, 0xe8, 0xf6, 0xf2,
	0x7c, 0xfa, 0x5d, 0x1f, 0x3d, 0x43, 0xf1, 0xac, 0xa1, 0xc4, 0x35, 0x74, 0xd2, 0xc3, 0xee, 0x99,
	0x33, 0xff, 0x1b, 0x14, 0x6f, 0xb4, 0xc3, 0xe2, 0x10, 0x12, 0x33, 0xb8, 0x62, 0xd1, 0xfc, 0x5d,
	0x84, 0x6a, 0xb3, 0x71, 0xe7, 0xb9, 0x84, 0xd4, 0x1a, 0x2b, 0xf2, 0xc6, 0xcb, 0xba, 0xda, 0x6e,
	0x7c, 0xd7, 0xf7, 0xff, 0xcc, 0x82, 0x9d, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x41, 0xe6, 0xf1,
	0x96, 0x8d, 0x02, 0x00, 0x00,
}
