---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: login-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /login
        backend:
          serviceName: login-service
          servicePort: 1323
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: static-login-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /static
        backend:
          serviceName: login-service
          servicePort: 1323
      - path: /auth
        backend:
          serviceName: login-service
          servicePort: 1323
